version: '3'
services:
  kafka:
    image: "spotify/kafka"
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
  generator:
    build: ./generator/
    image: hardishw/generator
    depends_on:
      - kafka
    command: ["-type=stream","-time=60","-topic=testTopic"]
  counter:
    build: ./counter/
    image: hardishw/counter
    depends_on:
      - kafka
    command: ["-topic=testTopic"]
