version: '3'
services:
  kafka:
    image: "spotify/kafka"
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
  generator:
    build: ./generator/
    image: hardishw/generator
